import path from 'path';
import { readJSON, readFile, writeFile, fileExists } from '../utils/fs';
import { log, printBanner, riskText } from '../utils/render';
import { LATEST_SNAPSHOT, LATEST_AUDIT_JSON, REPORTS_DIR } from '../utils/paths';
import { nowISO, nowTimestamp } from '../utils/time';
import { SnapshotData } from './snapshot';
import { AuditResult } from './audit';
import { RiskLevel } from '../utils/risk';

function nextSteps(riskLevel: RiskLevel): string {
  if (riskLevel === 'HIGH') {
    return [
      '- **STOP** — do not continue until you have manually reviewed all changes.',
      '- Check every high-risk file listed in the audit.',
      '- Verify no auth/billing/env/deployment files were modified without intent.',
      '- Consider reverting unintended changes with `git checkout <file>`.',
      '- Run your full test suite before merging.',
    ].join('\n');
  }
  if (riskLevel === 'MEDIUM') {
    return [
      '- Review all package/config changes carefully.',
      '- Confirm any dependency changes were intentional.',
      '- Run `npm install` if package.json changed, then test.',
      '- Run your full test suite.',
    ].join('\n');
  }
  return [
    '- Review the diff: `git diff`',
    '- Run your build: `npm run build`',
    '- Run your tests.',
    '- If everything looks good, commit the changes.',
  ].join('\n');
}

function buildReport(
  snapshot: SnapshotData,
  audit: AuditResult,
  taskScope: string | null,
  agentRules: string | null,
): string {
  const lines: string[] = [];

  lines.push('# AI Coding Run Report');
  lines.push('');
  lines.push(`*Generated by RepoBlackbox on ${nowISO()}*`);
  lines.push('');

  lines.push('---');
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Snapshot label | ${snapshot.label} |`);
  lines.push(`| Snapshot created | ${snapshot.createdAt} |`);
  lines.push(`| Audited at | ${audit.auditedAt} |`);
  lines.push(`| Branch | ${audit.git.branch ?? 'unknown'} |`);
  lines.push(`| Commit | ${audit.git.commit?.slice(0, 8) ?? 'unknown'} |`);
  lines.push(`| Risk level | **${audit.riskLevel}** |`);
  lines.push(`| Files added | ${audit.added.length} |`);
  lines.push(`| Files modified | ${audit.modified.length} |`);
  lines.push(`| Files deleted | ${audit.deleted.length} |`);
  lines.push(`| Risk flags | ${audit.flags.length} |`);
  lines.push('');

  // Task Scope
  lines.push('## Task Scope');
  lines.push('');
  if (taskScope) {
    lines.push(taskScope.trim());
  } else {
    lines.push('*No TASK_SCOPE.md found. Run `repoblackbox scope` before the next session.*');
  }
  lines.push('');

  // Changed Files
  lines.push('## Changed Files');
  lines.push('');

  if (audit.added.length > 0) {
    lines.push(`### Added (${audit.added.length})`);
    audit.added.forEach(f => lines.push(`- \`${f}\``));
    lines.push('');
  }

  if (audit.modified.length > 0) {
    lines.push(`### Modified (${audit.modified.length})`);
    audit.modified.forEach(f => lines.push(`- \`${f}\``));
    lines.push('');
  }

  if (audit.deleted.length > 0) {
    lines.push(`### Deleted (${audit.deleted.length})`);
    audit.deleted.forEach(f => lines.push(`- \`${f}\``));
    lines.push('');
  }

  if (audit.added.length === 0 && audit.modified.length === 0 && audit.deleted.length === 0) {
    lines.push('No file changes detected between snapshot and current state.');
    lines.push('');
  }

  // Scope Violations (dedicated section when present)
  if (audit.scopeViolations && audit.scopeViolations.length > 0) {
    lines.push('## Scope Violations');
    lines.push('');
    lines.push('> These files were changed but match patterns declared as **forbidden** in the task scope.');
    lines.push('');
    audit.scopeViolations.forEach(v => lines.push(`- ⛔ ${v}`));
    lines.push('');
  }

  if (audit.outOfScopeFiles && audit.outOfScopeFiles.length > 0) {
    lines.push('## Out-of-Scope Changes');
    lines.push('');
    lines.push('> These files were changed but are not covered by the declared **allowed** patterns.');
    lines.push('');
    audit.outOfScopeFiles.forEach(f => lines.push(`- ⚠️  \`${f}\``));
    lines.push('');
  }

  // Risk Flags
  lines.push('## Risk Flags');
  lines.push('');
  if (audit.flags.length > 0) {
    audit.flags.forEach(f => lines.push(`- ⚠️  ${f}`));
  } else {
    lines.push('No risk flags raised.');
  }
  lines.push('');

  // Review Checklist
  lines.push('## Review Checklist');
  lines.push('');
  lines.push('- [ ] Changed files match the task scope');
  lines.push('- [ ] No protected files were edited without approval');
  lines.push('- [ ] No environment files (.env) were read or modified');
  lines.push('- [ ] No auth/billing/deployment files were touched unintentionally');
  lines.push('- [ ] Any package.json / lock file changes are intentional');
  lines.push('- [ ] Build passes locally');
  lines.push('- [ ] Tests pass');
  lines.push('- [ ] Existing features are not broken');
  lines.push('');

  // Next Steps
  lines.push('## Suggested Next Steps');
  lines.push('');
  lines.push(nextSteps(audit.riskLevel));
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Report generated by [RepoBlackbox](https://github.com/stephenywilson/RepoBlackbox) — AI coding agent safety layer*');
  lines.push('');

  return lines.join('\n');
}

export function runReport(): void {
  printBanner('report — Generating AI coding run report');

  const snapshot = readJSON<SnapshotData>(LATEST_SNAPSHOT);
  if (!snapshot) {
    log.error('No snapshot found. Run "repoblackbox snapshot \\"label\\"" first.');
    process.exit(1);
  }

  const audit = readJSON<AuditResult>(LATEST_AUDIT_JSON);
  if (!audit) {
    log.error('No audit found. Run "repoblackbox audit" first.');
    process.exit(1);
  }

  const taskScope = readFile('TASK_SCOPE.md');
  const agentRules = readFile('AGENT_RULES.md');

  log.info(`Building report for: "${snapshot.label}"`);
  log.info(`Risk level: ${audit.riskLevel}`);

  const reportMd = buildReport(snapshot, audit, taskScope, agentRules);

  const ts = nowTimestamp();
  const stampedPath = path.join(REPORTS_DIR, `${ts}-report.md`);
  const latestPath = path.join(REPORTS_DIR, 'latest-report.md');

  writeFile(stampedPath, reportMd);
  writeFile(latestPath, reportMd);

  log.success(`Report saved: ${stampedPath}`);
  log.success(`Updated: ${latestPath}`);

  console.log();
  log.info(`Risk level: ${audit.riskLevel}`);
  if (audit.riskLevel === 'HIGH') {
    log.warn('HIGH risk — stop and review before continuing.');
  } else if (audit.riskLevel === 'MEDIUM') {
    log.warn('MEDIUM risk — check package/config changes carefully.');
  } else {
    log.info('LOW risk — review diff and run build/test.');
  }
  console.log();
}
