import readline from 'readline';
import { writeFile, writeJSON } from '../utils/fs';
import { log, printBanner } from '../utils/render';
import { RUNS_DIR, LATEST_SCOPE_JSON } from '../utils/paths';
import { nowISO, nowTimestamp } from '../utils/time';
import { parsePatternList } from '../utils/pattern';

interface ScopeOptions {
  task?: string;
  allow?: string;
  forbid?: string;
  success?: string;
}

export interface ScopeData {
  task: string;
  allowed: string[];
  forbidden: string[];
  success: string[];
  createdAt: string;
}

function buildScopeMarkdown(opts: {
  task: string;
  allow: string;
  forbid: string;
  success: string;
  createdAt: string;
}): string {
  return `# Task Scope

> Generated by RepoBlackbox on ${opts.createdAt}
> Paste this into Claude Code / Codex / Cursor before starting.

---

## Task

${opts.task || '(not specified)'}

## Allowed Files / Patterns

The AI agent may only edit files matching these paths or patterns:

\`\`\`
${opts.allow || '(not specified — be explicit)'}
\`\`\`

## Forbidden Files / Patterns

The AI agent must NOT touch these files under any circumstances:

\`\`\`
${opts.forbid || '.env\n.env.*\npackage.json\npackage-lock.json\npnpm-lock.yaml\nyarn.lock\nbun.lockb\nsrc/lib/auth/**\nsrc/lib/billing/**'}
\`\`\`

## Success Criteria

The task is complete when:

${opts.success || '(not specified)'}

## Notes for the Agent

- Read AGENT_RULES.md before starting.
- Keep changes minimal and scoped to the allowed files above.
- Do not rewrite unrelated modules.
- Do not delete existing functionality.
- After editing, list every changed file and explain why it changed.
- If you are unsure whether to touch a file, do not touch it.

---

*Scope defined via \`repoblackbox scope\`*
`;
}

async function promptUser(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function gatherInteractive(): Promise<{
  task: string;
  allow: string;
  forbid: string;
  success: string;
}> {
  console.log();
  log.info('No flags provided — entering interactive mode.');
  log.dim('  Press Enter to skip any field.\n');

  const task = await promptUser('  Task description: ');
  const allow = await promptUser('  Allowed files/patterns (comma-separated): ');
  const forbid = await promptUser('  Forbidden files/patterns (comma-separated): ');
  const success = await promptUser('  Success criteria: ');

  return { task, allow, forbid, success };
}

export async function runScope(options: ScopeOptions): Promise<void> {
  printBanner('scope — Define task boundaries for the AI agent');

  let task = options.task ?? '';
  let allow = options.allow ?? '';
  let forbid = options.forbid ?? '';
  let success = options.success ?? '';

  const hasFlags = task || allow || forbid || success;

  if (!hasFlags) {
    const answers = await gatherInteractive();
    task = answers.task;
    allow = answers.allow;
    forbid = answers.forbid;
    success = answers.success;
  }

  if (!task) {
    log.warn('No task description provided. Scope file will be incomplete.');
  }

  const createdAt = nowISO();
  const ts = nowTimestamp();

  // Markdown for humans / AI agents
  const content = buildScopeMarkdown({ task, allow, forbid, success, createdAt });

  // Machine-readable JSON for audit
  const scopeData: ScopeData = {
    task,
    allowed: parsePatternList(allow),
    forbidden: parsePatternList(forbid),
    success: success ? [success] : [],
    createdAt,
  };

  // Root-level TASK_SCOPE.md — always overwrite
  writeFile('TASK_SCOPE.md', content);
  log.success('Updated TASK_SCOPE.md');

  // Timestamped markdown
  writeFile(`${RUNS_DIR}/${ts}-scope.md`, content);
  log.success(`Saved ${RUNS_DIR}/${ts}-scope.md`);

  // Latest markdown pointer
  writeFile(`${RUNS_DIR}/latest-scope.md`, content);
  log.success(`Updated ${RUNS_DIR}/latest-scope.md`);

  // Machine-readable JSON (used by audit for pattern matching)
  writeJSON(LATEST_SCOPE_JSON, scopeData);
  writeJSON(`${RUNS_DIR}/${ts}-scope.json`, scopeData);
  log.success(`Saved ${RUNS_DIR}/latest-scope.json`);

  console.log();
  if (scopeData.forbidden.length > 0) {
    log.info(`Forbidden patterns: ${scopeData.forbidden.join(', ')}`);
  }
  if (scopeData.allowed.length > 0) {
    log.info(`Allowed patterns:   ${scopeData.allowed.join(', ')}`);
  }
  console.log();
  log.info('Paste TASK_SCOPE.md into your AI agent before starting the session.');
  log.info('Then run: repoblackbox snapshot "before <task-name>"');
  console.log();
}
