import { SkillFile } from './types';

const VAR_RE = /\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}/g;

export function substituteVariables(
  body: string,
  vars: Record<string, string>,
): string {
  return body.replace(VAR_RE, (match, name) => {
    if (Object.prototype.hasOwnProperty.call(vars, name)) {
      return vars[name];
    }
    // Leave unresolved (optional/missing) placeholders intact.
    return match;
  });
}

export function renderSkill(
  skill: SkillFile,
  vars: Record<string, string>,
): string {
  const header = `> Generated by RepoBlackbox Skill Packs · Skill: ${skill.metadata.title}`;
  const body = substituteVariables(skill.body, vars);
  return `${header}\n\n${body}`;
}
